# Generated by Django 3.1.1 on 2021-02-26 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronimyc', models.CharField(max_length=64, verbose_name='Отчество')),
                ('age', models.PositiveSmallIntegerField(default=18, verbose_name='возраст')),
                ('sex', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=32, verbose_name='Ваш пол')),
                ('married', models.CharField(choices=[('h', 'холост'), ('m', 'замужем/женат'), ('d', 'разведен/разведена'), ('v', 'вдовец/вдова')], max_length=1, verbose_name='Семейное положение')),
                ('skills', models.TextField(blank=True, max_length=264, verbose_name='Навыки (знание программ)')),
                ('hobby', models.TextField(blank=True, max_length=264, verbose_name='Ваши увлечения')),
                ('tel', models.CharField(blank=True, max_length=11, verbose_name='телефон')),
                ('photo', models.ImageField(blank=True, upload_to='seeker_photo')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Соискатели',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, unique=True, verbose_name='название компании')),
                ('tel', models.CharField(blank=True, max_length=11, verbose_name='телефон')),
                ('short_description', models.TextField(verbose_name='краткое описание компании')),
                ('logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('web', models.CharField(blank=True, max_length=64, verbose_name='вебсайт компании')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Работодатели',
            },
        ),
    ]
