# Generated by Django 3.1.1 on 2021-04-05 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210405_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 16, 0, 37, 27136)),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 16, 0, 37, 32862)),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
