# Generated by Django 3.1.1 on 2021-04-06 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210405_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 5, 50, 33, 162331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 5, 50, 33, 167982)),
        ),
    ]
