# Generated by Django 3.1.1 on 2021-04-28 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20210406_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='failed_moderation',
            field=models.CharField(blank=True, max_length=512, verbose_name='поле заполняется в случае отклонения модерации'),
        ),
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='need_moderation', max_length=32, verbose_name='статус компании на сайте'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='failed_moderation',
            field=models.CharField(blank=True, max_length=512, verbose_name='поле заполняется в случае отклонения модерации'),
        ),
        migrations.AddField(
            model_name='seeker',
            name='status',
            field=models.CharField(choices=[('need_moderation', 'требуется модерация'), ('moderation_ok', 'модерация пройдена успешно'), ('moderation_reject', 'отклонено модератором')], default='need_moderation', max_length=32, verbose_name='статус соискателя на сайте'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 49, 34, 721220)),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 0, 49, 34, 727150)),
        ),
    ]
