# Generated by Django 3.2.3 on 2021-05-28 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20210428_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 0, 46, 8, 492134)),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 0, 46, 8, 498624)),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='married',
            field=models.CharField(choices=[('h', 'холост'), ('m', 'в браке'), ('d', 'в разводе')], max_length=1, verbose_name='Семейное положение'),
        ),
    ]
