# Generated by Django 3.1.1 on 2021-03-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, help_text='поле необязательное для заполнения', max_length=264, verbose_name='что мы предлагаем'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, help_text='поле необязательное для заполнения', max_length=4, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.CharField(blank=True, help_text='поле необязательное для заполнения', max_length=32, verbose_name='максимальный уровень з/п'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_salary',
            field=models.CharField(blank=True, help_text='поле необязательное для заполнения', max_length=32, verbose_name='минимальный уровень з/п'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('полная занятость', 'полная занятость'), ('частичная занятость', 'частичная занятость'), ('занятость по проекту', 'занятость по проекту'), ('удаленная работа', 'удаленная работа')], default='полная занятость', max_length=32, verbose_name='тип занятости'),
        ),
    ]
