# Generated by Django 3.1.1 on 2021-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_auto_20210310_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='fall_moderation',
            field=models.TextField(blank=True, max_length=254, verbose_name='Сообщение в случае непрохождения модерации вакансии'),
        ),
    ]
