# Generated by Django 3.1.1 on 2021-03-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0004_vacancy_fall_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, choices=[('руб.', 'руб.'), ('USD', 'USD')], help_text='поле необязательное для заполнения', max_length=4, verbose_name='валюта'),
        ),
    ]
