# Generated by Django 3.1.1 on 2021-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0005_auto_20210310_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(blank=True, help_text='поле необязательное для заполнения', max_length=1080, verbose_name='что мы предлагаем'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1080, verbose_name='описание / обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(max_length=1080, verbose_name='требования к кандидату'),
        ),
    ]
