# Generated by Django 3.2.3 on 2021-06-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20210625_2346'),
        ('workerapp', '0006_alter_sendresponse_resume'),
        ('employerapp', '0009_sendoffers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteResumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.employer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteresumes', to='workerapp.resume', verbose_name='избранное резюме')),
            ],
            options={
                'verbose_name_plural': 'Избранные резюме',
            },
        ),
    ]
