# Generated by Django 3.2.3 on 2021-06-25 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0010_favoriteresumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteresumes',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата добавления в избранное'),
        ),
    ]
