# Generated by Django 3.2.3 on 2021-07-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0011_favoriteresumes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteresumes',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='добавлен в избранное'),
        ),
    ]
