# Generated by Django 3.1.1 on 2021-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hobby',
            field=models.TextField(blank=True, help_text='поле необязательно для заполнения', max_length=512, verbose_name='Ваши увлечения'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, max_length=512, verbose_name='Ключевые навыки'),
        ),
    ]
