# Generated by Django 3.2.3 on 2021-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0003_auto_20210528_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeexperience',
            name='finish_date',
            field=models.DateField(blank=True, help_text='оставьте пустым если работаете по настоящее время', null=True, verbose_name='Конец работы'),
        ),
    ]
