# Generated by Django 3.2.3 on 2021-06-22 01:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0009_sendoffers'),
        ('workerapp', '0004_alter_resumeexperience_finish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='дата направления отклика')),
                ('cover_letter', models.TextField(blank=True, help_text='поле не обязательное', max_length=524, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('new', 'новое (не прочитано)'), ('read', 'прочитано')], default='new', max_length=32, verbose_name='статус направленного отклика на вакансию')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerapp.resume', verbose_name='выберите резюме, которое вы хотитенаправить работодателю')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.vacancy', verbose_name='отклик на вакансию')),
            ],
            options={
                'verbose_name_plural': 'Направленные отклики на размещенные вакансии',
            },
        ),
    ]
