# Generated by Django 3.2.3 on 2021-06-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0005_sendresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendresponse',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerapp.resume', verbose_name='выберите резюме, которое вы хотите направить работодателю'),
        ),
    ]
