# Generated by Django 3.2.3 on 2021-07-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0006_alter_sendresponse_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='добавлен в избранное'),
        ),
    ]
