# Generated by Django 3.2.3 on 2021-07-20 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20210720_1059'),
        ('employerapp', '0013_vacancy_is_favorite'),
        ('workerapp', '0007_resume_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='дата добавления в избранное')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.seeker')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerapp.vacancy')),
            ],
            options={
                'verbose_name_plural': 'Избранные вакансии',
            },
        ),
    ]
